name: Development Pipeline

on: 
  push:
    branches: 
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm run test
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VM_PORT }}
        script: |
          cd ~/apps/project-z-be
          git pull
          npm run build
          pm2 restart
