name: Development Pipeline

on: 
  push:
    branches: 
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
      - uses: actions/checkout@v4
        with:
          node-version: '18.xx'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
